/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <bootutil/sign_key.h>

/*
 * Even though this is in principle a Zephyr-specific file, the
 * simulator builds it and uses it as well. Because of that, we can't
 * use Kconfig symbols for key types, and have to rely on the MCUBoot
 * symbols (which Zephyr provides via this header, and the simulator
 * provides via the compiler command line).
 */
#include <mcuboot_config/mcuboot_config.h>

#if !defined(MCUBOOT_HW_KEY)
#if defined(MCUBOOT_SIGN_RSA) || defined(MCUBOOT_SIGN_EC256) || defined(MCUBOOT_SIGN_ED25519) || defined(MCUBOOT_SIGN_MASQ)
#define HAVE_KEYS
#if defined(MCUBOOT_SIGN_RSA)
extern const unsigned char rsa_pub_key[];
extern unsigned int rsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_EC256)
extern const unsigned char ecdsa_pub_key[];
extern unsigned int ecdsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_ED25519)
extern const unsigned char ed25519_pub_key[];
extern unsigned int ed25519_pub_key_len;
#elif defined(MCUBOOT_SIGN_MASQ)
extern const unsigned char quantropi_pub_key[];
extern unsigned int quantropi_pub_key_len;
extern const unsigned char quantropi_crt_der;
extern unsigned int quantropi_crt_der_len;
#endif
#endif

/*
 * NOTE: *_pub_key and *_pub_key_len are autogenerated based on the provided
 *       key file. If no key file was configured, the array and length must be
 *       provided and added to the build manually.
 */
#if defined(HAVE_KEYS)
const struct bootutil_key bootutil_keys[] = {
    {
#if defined(MCUBOOT_SIGN_RSA)
        .key = rsa_pub_key,
        .len = &rsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_EC256)
        .key = ecdsa_pub_key,
        .len = &ecdsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_ED25519)
        .key = ed25519_pub_key,
        .len = &ed25519_pub_key_len,
#elif defined(MCUBOOT_SIGN_MASQ)
        .key = quantropi_pub_key,
        .len = &quantropi_pub_key_len,
#endif
    },
};
const int bootutil_key_cnt = 1;
#endif /* HAVE_KEYS */
#else
unsigned int pub_key_len;
struct bootutil_key bootutil_keys[1] = {
    {
        .key = 0,
        .len = &pub_key_len,
    }
};
const int bootutil_key_cnt = 1;
#endif /* !MCUBOOT_HW_KEY */

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) || defined(MCUBOOT_ENCRYPT_EC256)
extern const unsigned char enc_priv_key[];
extern unsigned int enc_priv_key_len;
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
#elif defined(MCUBOOT_ENCRYPT_KW)
#error "Encrypted images with AES-KW is not implemented yet."
#elif defined(MCUBOOT_ENCRYPT_MASQ)
unsigned char enc_priv_key[144] = {0xe3,0xd5,0xb2,0x87,0xa0,0xcf,0x6b,0xd2,0xe3,0x46,0x21,0x87,0x31,0xe4,0x6b,0xe2,0x10,0xd1,0x5b,0xb7,0xec,0xe0,0xdf,0xf2,0xe6,0xb6,0x96,0x35,0xf3,0x3c,0x74,0x79,0x91,0xf7,0x4e,0x6b,0xf0,0xe8,0x74,0x7e,0xd5,0x27,0xd5,0x2b,0xba,0x54,0xda,0x38,0xaf,0x76,0xbc,0x02,0x01,0x91,0x6a,0xbc,0xc7,0xdf,0xbe,0x80,0xb7,0x01,0xd5,0xb0,0x3c,0x81,0xda,0x3d,0xa1,0x38,0x5a,0x30,0x5a,0x9c,0xf4,0x4d,0x7b,0x19,0xce,0x93,0xec,0x86,0xf4,0x4d,0x75,0xd2,0xce,0x6c,0x96,0xeb,0xe9,0xa6,0x96,0x5d,0xa0,0xd3,0x80,0xba,0x66,0xae,0xaf,0x31,0xc4,0x7c,0x97,0xf1,0x1e,0x73,0x28,0x0d,0xb5,0x15,0x72,0xe0,0xd9,0x77,0xc0,0xa9,0x9c,0x58,0x1f,0x31,0x3d,0xee,0xb2,0xd6,0x9f,0x19,0x45,0xaf,0x9c,0x70,0xde,0x10,0x61,0x9a,0xab,0x54,0x7d,0x89,0x9f,0x0b,0x50,0xec};
unsigned int enc_priv_key_len = 144;
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
#endif
