CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=120000

CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="mcuboot-mbedtls-cfg.h"
CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n

CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_BOOTSTRAP=n

CONFIG_FLASH=y

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y # former CONFIG_MODE_MINIMAL
### Ensure Zephyr logging changes don't use more resources
CONFIG_LOG_DEFAULT_LEVEL=0
### Use info log level by default
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
### Decrease footprint by ~4 KB in comparison to CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_NANO=y
### Use the minimal C library to reduce flash usage
CONFIG_MINIMAL_LIBC=y

CONFIG_BOOT_SIGNATURE_TYPE_MASQ=y
CONFIG_MBEDTLS_TLS_1_3_MASQ_PPK=y
CONFIG_MBEDTLS_TLS_1_3_MASQ_ML=y

#malloc
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=100240
CONFIG_COMMON_LIBC_MALLOC=y

CONFIG_FPU=y
CONFIG_FP_HARDABI=y

CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=256

CONFIG_MEASURED_BOOT=y
CONFIG_MEASURED_BOOT_MAX_CBOR_SIZE=128